# Site settings
title: Sanjeet Kanwar
email: contact@sanjeet.com.au
description: "Freelance Web Developer located in Sydney"
blurb: "<strong>Sanjeet Kanwar</strong>"

#Build settings
markdown: kramdown
permalink: pretty

port: 4000

# Sass settings
sass:
    sass_dir: assets/css/_sass